baseURL: "/"
languageCod: en-us
title: Platform.sh Demos
theme: modular-reveal

pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsStyle: github

enableGitInfo: true



# If build on a local Hugo version > 0.60, uncomment this block to
# render slides correctly.
# markup:
#   goldmark:
#     renderer:
#       unsafe: true
