baseURL: "/"
languageCod: en-us
title: Platform.sh Demos
# theme: modular-reveal

# pygmentsCodeFences: true
# pygmentsUseClasses: false
# pygmentsStyle: dracula

enableGitInfo: true



# If build on a local Hugo version > 0.60, uncomment this block to
# render slides correctly.
markup:
  # defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
